/**
 * Learning Center content — buyer/seller guides + glossary.
 *
 * Content-as-data (no DB). Bodies are lightweight markdown-ish paragraphs the
 * article page renders. Coverage intentionally includes UAE/Canada financing
 * specifics (CSBFP, BDC, Murabaha, Ijara) that BizBuySell's US-centric resource
 * center omits.
 */

export type ArticleCategory = 'Buying' | 'Selling' | 'Financing' | 'Valuation' | 'Legal & Deal-Making'

export interface Article {
  slug: string
  title: string
  category: ArticleCategory
  region?: 'USA' | 'CANADA' | 'UAE' | 'BOTH' | 'ALL'
  readMinutes: number
  excerpt: string
  body: string[] // paragraphs / headers (lines starting with "## " render as headings)
}

export const ARTICLES: Article[] = [
  {
    slug: 'how-to-buy-a-business',
    title: 'How to Buy a Business: A Step-by-Step Guide',
    category: 'Buying',
    region: 'BOTH',
    readMinutes: 8,
    excerpt: 'From defining acquisition criteria to closing — the full buyer journey for the UAE and Canadian markets.',
    body: [
      '## 1. Define your acquisition criteria',
      'Decide on industry, location, deal size, and the cash flow you need. Save your criteria as a search on ForwardOS to get alerted the moment a matching business lists.',
      '## 2. Get pre-qualified for financing',
      'Knowing your budget up front makes you a credible buyer. In Canada, explore CSBFP and BDC acquisition loans; in the UAE, SME and Sharia-compliant facilities. Use the Finance Center calculator to size your monthly payment.',
      '## 3. Review listings and request information',
      'Shortlist businesses, sign NDAs, and request the data room. Look for clean financials, customer concentration, and the reason for sale.',
      '## 4. Make an offer (LOI)',
      'A Letter of Intent sets price and key terms and opens exclusivity for due diligence. It is usually non-binding except for confidentiality and exclusivity clauses.',
      '## 5. Due diligence',
      'Verify financials, contracts, licences, and liabilities. Engage an accountant and lawyer. This is where financing is finalised.',
      '## 6. Close',
      'Sign the purchase agreement, fund the deal, and transfer licences and ownership. Plan a transition period with the seller.',
    ],
  },
  {
    slug: 'how-to-sell-your-business',
    title: 'How to Sell Your Business for Maximum Value',
    category: 'Selling',
    region: 'BOTH',
    readMinutes: 7,
    excerpt: 'Preparation, pricing, and presentation strategies that drive more qualified buyers and higher offers.',
    body: [
      '## Get your house in order',
      'Clean, three-year financials and documented processes build buyer confidence. The more complete your ForwardOS listing, the more inquiries you attract — completeness correlates directly with buyer interest.',
      '## Price with evidence',
      'Use comparable sales and a defensible multiple. Overpricing lengthens days-on-market; underpricing leaves money on the table. See the Market Insights report for current regional multiples.',
      '## Present professionally',
      'Strong photos, a clear growth story, and an honest risk section. Consider a verified listing to signal legitimacy.',
      '## Qualify buyers',
      'Prioritise financed, serious buyers. ForwardOS scores buyer seriousness so you spend time on the right conversations.',
    ],
  },
  {
    slug: 'financing-a-business-acquisition-canada',
    title: 'Financing a Business Acquisition in Canada (CSBFP & BDC)',
    category: 'Financing',
    region: 'CANADA',
    readMinutes: 6,
    excerpt: 'How the Canada Small Business Financing Program and BDC acquisition loans work — and how to qualify.',
    body: [
      '## Canada Small Business Financing Program (CSBFP)',
      'A government-backed program delivered through major banks (RBC, BMO, Scotiabank, TD, CIBC). It shares risk with the lender, helping fund equipment, property, and business purchases up to $1.15M.',
      '## BDC acquisition financing',
      'The Business Development Bank of Canada offers dedicated acquisition and transition loans with flexible repayment and no penalty for early repayment — useful for cash-flowing businesses.',
      '## What lenders look for',
      'A debt-service coverage ratio of 1.25× or higher, a reasonable down payment (often 20-30%), and a credible transition plan. Model yours in the Finance Center calculator.',
    ],
  },
  {
    slug: 'islamic-financing-business-uae',
    title: 'Sharia-Compliant Business Financing in the UAE',
    category: 'Financing',
    region: 'UAE',
    readMinutes: 6,
    excerpt: 'Murabaha and Ijara explained — how to fund an acquisition without interest (riba).',
    body: [
      '## Why Islamic financing matters',
      'Many UAE buyers require Sharia-compliant structures. These avoid riba (interest) and instead use asset-based, profit-sharing arrangements agreed up front.',
      '## Murabaha (cost-plus)',
      'The financier buys the asset and resells it to you at a disclosed mark-up, repaid in instalments. The total is fixed at the outset — no compounding interest.',
      '## Ijara (lease-to-own)',
      'The financier owns the asset and leases it to you; ownership transfers at the end of the term. Common for equipment- and property-heavy businesses.',
      '## Where to start',
      'Dubai Islamic Bank, ADCB Islamic, and Sharia-compliant platforms like Beehive offer these products. Filter for "Sharia-compliant" in the Finance Center.',
    ],
  },
  {
    slug: 'understanding-business-valuation',
    title: 'Understanding Business Valuation: SDE, EBITDA & Multiples',
    category: 'Valuation',
    region: 'BOTH',
    readMinutes: 7,
    excerpt: 'The core methods buyers and sellers use to price small and mid-sized businesses.',
    body: [
      '## Seller\'s Discretionary Earnings (SDE)',
      'For owner-operated businesses, SDE adds back the owner\'s salary and discretionary expenses to show the true earnings available to a single owner-operator.',
      '## EBITDA',
      'Earnings before interest, taxes, depreciation, and amortisation — the standard for larger, manager-run businesses. Buyers apply an industry multiple to EBITDA.',
      '## Multiples',
      'Price is often expressed as a multiple of SDE, EBITDA, or revenue. Multiples vary by industry, growth, and risk — see current regional ranges in Market Insights.',
      '## Adjustments matter',
      'Normalise one-off costs, owner add-backs, and working capital. A well-supported adjustment can materially change the headline price.',
    ],
  },
  {
    slug: 'letter-of-intent-and-due-diligence',
    title: 'The LOI and Due Diligence: What to Expect',
    category: 'Legal & Deal-Making',
    region: 'BOTH',
    readMinutes: 6,
    excerpt: 'How a Letter of Intent frames the deal and what buyers verify before closing.',
    body: [
      '## The Letter of Intent (LOI)',
      'A mostly non-binding document setting price, structure, and timelines, with binding confidentiality and exclusivity. It signals serious intent and starts the diligence clock.',
      '## Due diligence checklist',
      'Financial statements and tax returns, customer and supplier contracts, licences and permits, employee agreements, litigation, and asset ownership. Use a secure data room to share documents and track access.',
      '## Common deal structures',
      'Asset purchase vs share purchase, earnouts, and seller financing (vendor take-back). Each has tax and liability implications — involve a lawyer early.',
    ],
  },
  // ====================== 10 NEW LONG-FORM ARTICLES ======================
  {
    slug: 'how-to-value-a-business',
    title: 'How to Value a Business: A Complete 2026 Guide',
    category: 'Valuation',
    region: 'ALL',
    readMinutes: 12,
    excerpt: 'The four valuation methods buyers and sellers actually use — with examples, the multiples that matter, and the adjustments that move the headline price.',
    body: [
      '## Why valuation matters',
      'Pricing a business correctly is the single biggest driver of a successful sale. Overpricing kills buyer interest and lengthens days-on-market; underpricing leaves real money on the table. The good news: most small and lower-mid-market businesses are valued using a small set of well-understood methods.',
      '## Method 1: SDE multiples (owner-operated businesses)',
      'For businesses where one owner runs day-to-day operations, the standard measure is Seller\'s Discretionary Earnings (SDE): net income plus the owner\'s salary, plus non-cash and one-off expenses. Apply an industry multiple — typically 2.0×–3.5× SDE for service businesses, 1.5×–2.5× for restaurants, 2.5×–4× for established e-commerce.',
      '## Method 2: EBITDA multiples (manager-run businesses)',
      'For larger businesses with non-owner managers, EBITDA (Earnings Before Interest, Taxes, Depreciation, and Amortization) is the standard. Multiples vary widely: 3×–5× for distribution and services, 5×–8× for healthcare and specialty manufacturing, 4×–7× for industrial, 5×–10× for SaaS depending on growth and retention.',
      '## Method 3: Revenue multiples',
      'Used primarily for early-stage, fast-growth, or recurring-revenue businesses where profit is small or reinvested. Common ranges: 0.5×–1.5× for low-margin services, 1×–3× for established e-commerce, 2×–6× ARR for SaaS depending on growth, gross retention, and net retention.',
      '## Method 4: Discounted Cash Flow (DCF)',
      'A forward-looking method projecting 5–10 years of free cash flow and discounting back to present value. Common in lower-mid-market and PE deals but sensitive to assumptions — most SMB transactions cross-check DCF against the comparable-multiple methods above.',
      '## Adjustments that change the price',
      'Few buyers pay the headline number. Material adjustments include: working-capital "peg" (the normalized working capital that comes with the business — anything above is paid out at close, anything below reduces price); customer concentration (>20–25% from one customer typically warrants a discount); owner add-backs (legitimate vs aggressive); deferred capex; and lease economics. Each can shift price by 10–30%.',
      '## Quick-and-dirty: the rule of thumb',
      'For a fast first estimate: SDE × industry multiple + value of saleable inventory and equipment. Cross-check against revenue × industry multiple. If the two numbers are within ~20%, you have a defensible starting range. If they\'re far apart, dig into why.',
      '## Get a free range on Forward',
      'Every Forward Intelligence listing carries an AI-generated valuation range based on comparables, financials, and growth signals. Sellers see it free during listing prep; buyers see it as a deal-quality signal alongside our heat score.',
    ],
  },
  {
    slug: 'how-to-write-a-letter-of-intent',
    title: 'How to Write a Winning Letter of Intent (LOI) — With Template',
    category: 'Legal & Deal-Making',
    region: 'ALL',
    readMinutes: 9,
    excerpt: 'The LOI is the moment the deal becomes real. Here\'s what to include, what to leave out, and a clause-by-clause template you can copy.',
    body: [
      '## What a Letter of Intent actually does',
      'The LOI is the bridge between casual interest and signed legal documents. It sets price, structure, and timeline; it grants the buyer exclusivity to run due diligence; and it keeps the seller from running parallel negotiations. Most LOIs are non-binding on the deal itself, but binding on confidentiality and exclusivity — read every clause carefully.',
      '## The 9 sections a good LOI contains',
      '- Parties and structure (who is buying what — assets, shares, or a holdco)',
      '- Purchase price and how it will be paid (cash at close, seller note, earnout, escrow)',
      '- Working-capital treatment (the "peg" and how excess/shortfall is handled)',
      '- Contingencies (financing, satisfactory due diligence, key-employee retention)',
      '- Exclusivity period (usually 30–60 days)',
      '- Confidentiality (binding — survives termination)',
      '- Conditions to closing (regulatory, third-party consents)',
      '- Expense allocation (each party usually pays its own advisors)',
      '- Governing law and dispute resolution',
      '## Clauses worth fighting over',
      'Exclusivity length is the buyer\'s leverage — sellers should resist anything over 60 days. The working-capital peg is where 80% of post-LOI fights happen — agree on the methodology (e.g., trailing 12-month average) in the LOI, not afterward. Earnout language must be specific: who controls the business during the earnout, what protections exist for the seller, and what counts as a "qualifying" sale.',
      '## What NOT to include',
      'Don\'t put your final price in the first draft if you have room — start 10–15% below your walk-away. Don\'t agree to a no-shop without exclusivity expiration. Don\'t skip the financing contingency unless you\'re writing a cash check.',
      '## Template (copy and adapt — get counsel review)',
      'Dear [Seller], This Letter of Intent ("LOI") summarizes the terms under which [Buyer] proposes to acquire [Target]. The proposed purchase price is $[X], payable [structure]. Working capital at closing shall be [peg]. This LOI is contingent on [diligence/financing]. The parties agree to a [60]-day exclusivity period, during which Seller will not solicit or accept other offers. Confidentiality obligations under our [NDA dated X] survive termination of this LOI. Each party shall bear its own expenses. This LOI is non-binding except for sections [Exclusivity, Confidentiality, Expenses, Governing Law].',
      '## What happens next',
      'Once both parties sign, due diligence begins. Sellers should populate their data room before signing so day-1 of diligence is productive. Buyers should issue a comprehensive document request within 48 hours of signing — the exclusivity clock is ticking.',
    ],
  },
  {
    slug: 'sba-loan-vs-seller-financing',
    title: 'SBA Loan vs Seller Financing: Which Is Better for Your Acquisition?',
    category: 'Financing',
    region: 'USA',
    readMinutes: 10,
    excerpt: 'Most U.S. business buyers use a blend. Here\'s when SBA wins, when seller carry wins, and how to structure both for the same deal.',
    body: [
      '## The short answer',
      'It\'s rarely either/or. The most common SMB deal structure in 2026: SBA 7(a) for 70–80% of the purchase, 10–20% buyer equity, and 10–20% seller carry. Each piece does something the others can\'t.',
      '## SBA 7(a): the workhorse',
      'Up to $5M, 10-year terms (25 years if real estate is involved), as little as 10% down for qualified buyers, and rates typically Prime + 2.75–4.75%. The trade-off: 60–90 days to close, personal guarantee from anyone owning >20%, and meaningful underwriting friction (3 years of seller tax returns, business valuation, environmental review).',
      '## Seller financing: the lubricant',
      'A "seller note" — the seller takes back 10–20% of the purchase as a 5–7 year subordinated note. Why both sides like it: buyers get a smaller equity check and a signal the seller believes in the business; sellers get a stream of post-close income (often at 5–7% interest) and a stronger price.',
      '## When SBA wins',
      'Lower interest cost (vs seller carry rates of 5–7%), longer amortization (lower monthly payment), and standardized terms. SBA wins decisively when the business has clean books, the buyer has decent credit, and the seller wants cash at close.',
      '## When seller carry wins (or fills a gap)',
      'Faster close (no SBA underwriting). Bridges valuation gaps — if the buyer can\'t get the bank up to the seller\'s asking price, a larger seller note unlocks the deal. Also essential when the SBA limit is binding (e.g., $6M deal where SBA caps at $5M).',
      '## How to structure a blend',
      'Example $2M deal: $1.4M SBA 7(a) (10-year, ~10.5%), $300K buyer equity (15%), $300K seller note (5-year, 6%, payments deferred 6 months). Monthly cost roughly $19K, supported by ~$28K of business cash flow — DSCR ~1.5×, comfortably bankable.',
      '## The seller carry trick most buyers miss',
      'Negotiate a "standby" period — seller note payments don\'t begin for 6–12 months. This protects cash flow during transition and is something seasoned SBA lenders actively prefer (it strengthens the credit). Most sellers will accept this if the rate is reasonable.',
      '## Model both in our Finance Center',
      'Use the Finance Center calculator to model SBA, seller-carry, and a blended structure side-by-side. We\'ll show you the DSCR, total interest cost, and monthly payment for each.',
    ],
  },
  {
    slug: 'business-due-diligence-checklist',
    title: 'Due Diligence Checklist: 47 Things to Verify Before Buying a Business',
    category: 'Buying',
    region: 'ALL',
    readMinutes: 14,
    excerpt: 'The complete, no-fluff checklist used by experienced acquirers. Organized by week, with the red flags that should make you walk.',
    body: [
      '## Why this list exists',
      'Most failed acquisitions can be traced to something the buyer should have caught in due diligence. This checklist covers the 47 verification items that matter — organized so you can sequence them across a typical 30–45 day diligence period.',
      '## Week 1: financial verification',
      '- 3 years of tax returns (vs internal statements — variances >5% need explanation)',
      '- Trailing 12-month P&L by month (look for seasonality, declining trends)',
      '- Balance sheet at month-end for the last 12 months',
      '- Bank statements (verify deposits match revenue)',
      '- A/R aging (anything >90 days is suspect)',
      '- A/P aging (vendors stretched? deferred payments?)',
      '- Inventory listing with age and turnover by SKU',
      '- All add-backs documented with receipts',
      '## Week 2: customers and contracts',
      '- Top-10 customer list with revenue % (concentration risk)',
      '- Customer retention rates (logo and revenue)',
      '- All customer contracts (assignment clauses matter — does sale trigger termination?)',
      '- Any contracts up for renewal in next 12 months',
      '- Sales pipeline and recent win/loss',
      '- Any customer disputes, chargebacks, or open complaints',
      '- Marketing spend efficiency (CAC, payback)',
      '## Week 3: operations and people',
      '- Employee roster: roles, salaries, tenure, contract types',
      '- Non-compete and confidentiality agreements in place?',
      '- Key-employee retention plan (who walks if the deal closes?)',
      '- Org chart and owner-dependence assessment',
      '- Lease(s): term, renewal options, assignment rights, rent escalators',
      '- Equipment list with age, condition, and remaining useful life',
      '- Inventory of intellectual property (trademarks, software, processes)',
      '- IT systems and licenses (transferable on sale?)',
      '- Insurance policies and recent claims',
      '## Week 4: legal, regulatory, environmental',
      '- Corporate records and good-standing certificates',
      '- All licenses and permits (transferable?)',
      '- Pending or threatened litigation',
      '- Tax compliance (sales tax, payroll tax, federal/state filings)',
      '- Environmental assessments (manufacturing, F&B, anything with hazardous materials)',
      '- HR compliance (wage and hour, worker classification)',
      '- Privacy/data handling (especially relevant in healthcare, financial)',
      '- Any regulatory inquiries or open investigations',
      '## Throughout: cultural & operational reality check',
      '- On-site visit (minimum 1 day; for retail/hospitality, 2–3 days at different times)',
      '- Customer interviews (with seller\'s permission, late in process)',
      '- Vendor calls (verify pricing, payment terms, relationship strength)',
      '- Employee interviews post-LOI (carefully)',
      '## Red flags that should make you walk',
      'Cash sales materially exceed deposits (under-reported revenue). Customer concentration >40% in one account without long-term contract. Owner unwilling to provide a 90-day transition. Material litigation undisclosed at LOI. Inventory aged >12 months with no plan. Working-capital trends sharply negative over diligence period.',
      '## Bring in specialists',
      'Don\'t DIY everything. Engage: an accountant for QoE (Quality of Earnings) for deals >$1M; a lawyer for the purchase agreement; an environmental consultant if applicable. The $15–30K spent on a real QoE has saved more deals than any other line item.',
    ],
  },
  {
    slug: 'how-to-negotiate-business-purchase-price',
    title: 'How to Negotiate the Purchase Price of a Business (Without Losing the Deal)',
    category: 'Buying',
    region: 'ALL',
    readMinutes: 8,
    excerpt: 'Eight tactical moves experienced buyers use to lower price and improve terms — without coming across as adversarial.',
    body: [
      '## The principle',
      'Negotiation in M&A is almost never won by being aggressive. It\'s won by being prepared, anchoring early, and trading well across multiple variables (not just price). Here\'s what actually works.',
      '## Tactic 1: anchor with your LOI, not your final offer',
      'Open at 10–15% below your true willingness-to-pay. Sellers expect negotiation; opening at your walk-away leaves you nowhere to retreat. Make sure your LOI price is defensible with a one-line rationale ("based on [X]× SDE of $[Y]").',
      '## Tactic 2: trade across variables',
      'Price isn\'t the only lever. Working-capital peg, earnout structure, seller financing rate, transition period length, non-compete radius, escrow size — all can be traded against headline price. Most sellers care about the headline number more than the structure, so use that.',
      '## Tactic 3: use the working capital peg',
      'A trailing 12-month average peg vs a trailing 3-month peg can shift effective price by 5–10% in either direction. Insist on a methodology in the LOI; quietly select the one that favors you.',
      '## Tactic 4: tie earnouts to specific, controllable metrics',
      'If the seller is asking for an earnout, agree — but tie it to gross profit (not revenue) and put protections in place around your control of the business. Most overpriced deals get rationalized via earnouts the buyer never actually pays.',
      '## Tactic 5: let due diligence do the work',
      'Don\'t re-negotiate on day 1. Wait for diligence findings — every material issue (customer concentration, deferred capex, working-capital normalization, undisclosed liabilities) is a documented basis for price reduction. Frame it as "calibrating the price to what we discovered," not "we want a discount."',
      '## Tactic 6: never be the only bidder (or pretend not to be)',
      'Sellers price based on perceived demand. Reference comparable processes you\'re running (truthfully), reference your acquisition criteria (so the seller knows you have alternatives), and don\'t be the first to put a number on the table if you can avoid it.',
      '## Tactic 7: align on the WHY before haggling',
      'Sellers selling for retirement think differently than sellers selling for cash. Sellers selling because of partner conflict are more flexible than those who plan to roll equity. Understand the motivation before the negotiation — it tells you which variables matter.',
      '## Tactic 8: keep walking distance',
      'The single biggest source of buyer leverage is real willingness to walk. The single biggest source of bad deals is loss aversion ("we\'ve already spent $30K in diligence"). Set your walk-away price before LOI and don\'t move it without new information.',
      '## What to avoid',
      'Don\'t belittle the business. Don\'t haggle in the same email as a diligence finding (separate them). Don\'t fight on every line item — pick 3 big ones. Don\'t threaten unless you mean it.',
    ],
  },
  {
    slug: 'working-capital-adjustments-explained',
    title: 'Working Capital Adjustments Explained: The Hidden Cost of Buying a Business',
    category: 'Legal & Deal-Making',
    region: 'ALL',
    readMinutes: 8,
    excerpt: 'The working-capital "peg" is where most post-LOI fights happen — and where 5–10% of effective purchase price hides. Here\'s how it works.',
    body: [
      '## What the working-capital peg is',
      'Most M&A deals close on a "cash-free, debt-free" basis but assume the business comes with a normalized amount of working capital — enough to operate day-1. The "peg" is the dollar amount of working capital the buyer expects at close. Anything above is paid to the seller; anything below reduces the purchase price.',
      '## Why it matters',
      'For a $2M business, working capital can swing $200K–$400K month to month based on seasonality, customer payment timing, and inventory cycles. Without a peg, the seller could drain receivables and stretch payables right before close — handing you a business that needs $200K of working capital injection on day 1.',
      '## How the peg is set',
      'Standard methods (in order of frequency):',
      '- **Trailing 12-month average** — sums monthly working capital balances over the last year and divides by 12. Smooths seasonality. Most common.',
      '- **Trailing 6-month average** — more recent, but vulnerable to short-term swings.',
      '- **Last 3-month average** — useful for businesses with structural changes; risky for seasonals.',
      '- **Forward-looking budget** — only used when historical data is unreliable.',
      '## The components',
      'Working capital = (current assets — cash) — (current liabilities — debt). Specifically: accounts receivable + inventory + prepaid expenses, MINUS accounts payable + accrued expenses + deferred revenue. Cash and debt are handled separately on the cash-free/debt-free principle.',
      '## Where the fights happen',
      '- Is deferred revenue included? (Buyers want it counted as a liability; sellers want it excluded.)',
      '- Is excess/obsolete inventory at full value or written down? (Buyer wants writedowns.)',
      '- A/R older than 90 days — at face value, discounted, or excluded?',
      '- Accrued bonuses, vacation, and other employee liabilities — current period or whole accrual?',
      '## How it settles at close',
      'Estimated working capital is calculated 3–5 days before close. The purchase price is adjusted by (estimate — peg). Then 60–90 days post-close, a true-up: actual working capital at close vs the estimate, with cash flowing between parties. Escrow ($50–150K typical) is often held back for this.',
      '## Buyer tactics',
      'Insist on a 12-month average methodology with explicit treatment of A/R aging and inventory writedowns. Get an example calculation in the LOI based on the most recent month. Require the seller to maintain "ordinary course" working capital during diligence (no draining A/R, no stretching A/P).',
      '## Seller tactics',
      'Push for a recent (3- or 6-month) average if working capital has been declining. Define "ordinary course" precisely. Cap any post-close adjustment at a reasonable amount (e.g., $100K). Don\'t agree to a peg before seeing the methodology in writing.',
      '## What to remember',
      'The peg is not academic. On a typical SMB deal, it\'s worth 3–8% of purchase price. Spend an extra hour on it in the LOI; you\'ll save days of fighting later.',
    ],
  },
  {
    slug: 'asset-sale-vs-share-sale',
    title: 'Asset Sale vs Share Sale: Which Structure Is Right for You?',
    category: 'Legal & Deal-Making',
    region: 'ALL',
    readMinutes: 9,
    excerpt: 'The single structure choice that affects taxes, liability, and which contracts transfer. Buyers and sellers usually want opposite things.',
    body: [
      '## The core difference',
      'In an **asset sale**, the buyer creates a new entity and buys specific assets and liabilities from the seller\'s company. The seller\'s entity continues to exist (and bears any liabilities not transferred). In a **share sale**, the buyer buys the equity of the seller\'s existing entity — everything inside it (assets, liabilities, contracts, history) comes along.',
      '## Why buyers prefer asset sales',
      'Liability protection (you don\'t inherit unknown debts, litigation, tax issues). Cherry-picking — you choose which assets and liabilities to take. Stepped-up tax basis on acquired assets (in the U.S., this allows higher depreciation deductions, lowering taxes for years post-close).',
      '## Why sellers prefer share sales',
      'Tax treatment — capital gains (typically lower rate) rather than ordinary income on certain asset categories. Cleaner exit (no surviving entity with stranded liabilities). One transfer, not dozens.',
      '## The U.S. tax dimension (talk to your CPA)',
      'In an asset sale, allocation matters: depreciable assets and inventory generate ordinary income to the seller; goodwill is capital gain. Buyers prefer high goodwill allocation; sellers prefer high inventory/depreciable allocation. The IRS Form 8594 captures the agreed allocation — both parties must file consistently.',
      '## Canadian considerations',
      'In Canada, the Lifetime Capital Gains Exemption (LCGE) makes share sales of Qualified Small Business Corporation (QSBC) shares particularly attractive to sellers — up to ~$1M of capital gains can be exempt. This makes Canadian SMB sellers materially prefer share deals — buyers usually pay a premium to compensate (5–10%).',
      '## UAE considerations',
      'Asset vs share matters for the trade-licence transfer mechanism (mainland DED vs free zone). Free-zone transfers often happen at the share level for licensing simplicity; mainland deals are more frequently structured as asset transfers. Visa/Emirates ID continuity for employees is a key practical consideration.',
      '## What contracts come along',
      '**Share sale:** all contracts continue (the legal entity is unchanged). But many contracts have "change of control" clauses that trigger renewals or terminations — get a contract assignment review in diligence. **Asset sale:** contracts must be individually assigned, and most require counterparty consent. For a deal with 50+ customer contracts, getting consents can take weeks.',
      '## Liability — the big one',
      'In an asset sale, the buyer typically inherits only the liabilities specifically listed. But certain liabilities are nearly impossible to escape: product liability for previously-sold goods, environmental liability, certain employee obligations (especially in Canada/UAE), and tax liabilities (in some jurisdictions). Your purchase agreement\'s "Assumed Liabilities" and "Excluded Liabilities" sections deserve careful drafting.',
      '## How to decide',
      'Default to asset sale if you\'re the buyer and the seller\'s history isn\'t squeaky-clean. Default to share sale if you\'re a Canadian seller eligible for LCGE. Negotiate around the difference — typically a 5–10% price gap separates the two structures.',
    ],
  },
  {
    slug: 'find-off-market-businesses-for-sale',
    title: 'How to Find Off-Market Businesses for Sale (And Why They\'re Often the Best Deals)',
    category: 'Buying',
    region: 'ALL',
    readMinutes: 8,
    excerpt: 'The best businesses are often never listed. Here\'s the playbook serious acquirers use to source off-market deals.',
    body: [
      '## Why off-market matters',
      'Roughly 60% of small-business transactions happen off-market — either through broker relationships, direct outreach, or owner networks. The deals are often better priced (no competitive auction), better fit (matched to the buyer), and less stressful (longer timelines, more transparent sellers).',
      '## Tactic 1: define a tight buy-box',
      'Before sourcing, write your acquisition criteria on one page: industries, geography, size (revenue + EBITDA), owner-dependence threshold, and disqualifiers. A clear buy-box gets you 5× the responses on outreach because sellers and brokers can quickly tell if you\'re relevant.',
      '## Tactic 2: build a broker network (the highest-leverage move)',
      'M&A brokers know about deals 30–60 days before they hit the market. Reach out to 15–20 brokers in your target geographies/industries with your buy-box and proof of capability (capital, prior experience). Most will add you to their early-look list immediately.',
      '## Tactic 3: direct outreach',
      'Build a list of 200–500 businesses matching your criteria (using public corporate records, industry associations, LinkedIn, or paid databases like Capitalogix, Grata, Sourcescrub). Send a short, personalized letter or email — not a templated blast. Expected response rate: 1–3%. From 500 letters, 5–15 conversations, 1–3 serious processes.',
      '## Tactic 4: industry associations and events',
      'Industry trade associations are goldmines. Sponsor regional events, get invited to member dinners, build relationships with the executive directors. Most have unofficial "succession" lists they\'ll share with credible buyers.',
      '## Tactic 5: ex-employees and competitors',
      'People who recently left a target business know which owners are tired, which businesses are growing, which are struggling. Build relationships with executive recruiters in your target industries — they have visibility into everything.',
      '## Tactic 6: lender introductions',
      'SBA lenders and BDC representatives see business sales coming months in advance (because owners often refinance or get business valuations 6–12 months before listing). A relationship with a senior commercial banker in your target region is worth 50 cold emails.',
      '## Tactic 7: be the "first call"',
      'Many of the best deals never even get to outreach — they go to the buyer the seller already knew about. Be present in your target industry: write about it (LinkedIn, blogs), speak at events, mentor sellers. When a deal comes up, you\'re the call.',
      '## Tactic 8: the patient close',
      'Off-market deals take 3–12 months from first contact to LOI. That\'s normal. Sellers need time to mentally commit to selling, family conversations, and emotional preparation. The buyer who shows up consistently over time wins.',
      '## What to avoid',
      'Don\'t blast generic outreach — sophisticated owners (the ones you want) can spot a template instantly. Don\'t lead with price. Don\'t push on timeline. Don\'t skip the qualifying questions early (you\'ll waste months on deals that aren\'t real).',
      '## How Forward Intelligence helps',
      'Set up a saved search with your buy-box and we\'ll alert you the moment a matching business lists. Our broker directory surfaces vetted advisors in your target regions and industries. And our buyer-seriousness signals tell sellers you\'re a credible counterparty — moving you up the list.',
    ],
  },
  {
    slug: 'buying-a-business-canada-vs-usa',
    title: 'Buying a Business in Canada vs USA: Key Differences Explained',
    category: 'Buying',
    region: 'BOTH',
    readMinutes: 9,
    excerpt: 'Tax structure, financing options, immigration paths, and regulatory differences for cross-border acquirers — what every buyer should know.',
    body: [
      '## Why the difference matters',
      'A $2M acquisition in Toronto can have materially different post-tax economics than the same $2M acquisition in Detroit. Both markets have great businesses; the wrapper is different.',
      '## Deal structure: asset vs share',
      'The U.S. heavily favors asset sales for tax (step-up in basis); Canadian sellers heavily favor share sales (Lifetime Capital Gains Exemption — up to ~$1M of capital gains exempt on Qualified Small Business Corporation shares). Canadian buyers pay a price premium of 5–10% to compensate sellers who give up the LCGE.',
      '## Financing',
      'U.S.: SBA 7(a) dominates ($5M cap, 10-year terms, ~10–12% rate, Prime + 2.75–4.75%). Canada: CSBFP ($1.15M cap, common for equipment/property/leaseholds) plus BDC acquisition loans (no hard cap, dedicated business-buyer products). Canadian rates are generally lower than U.S. for comparable deals.',
      '## Working capital and balance sheet',
      'GAAP differs slightly (U.S. GAAP vs Canadian ASPE / IFRS). Most material to buyers: revenue recognition timing, lease treatment, and inventory accounting. Get accountant cross-checks if you\'re a U.S. buyer reading Canadian financials (or vice versa).',
      '## Sales tax / VAT',
      'U.S.: state-level sales tax (varies by state and product). Canada: GST/HST (5–15% depending on province) and PST in some provinces. Sales tax compliance is a top diligence item in both countries.',
      '## Employment law',
      'Canada has stronger employee protections — termination notice is typically 1 month/year of service (common law) versus U.S. at-will employment. Severance liabilities materially larger in Canada — diligence carefully.',
      '## Immigration (for cross-border buyers)',
      'U.S.: E-2 Treaty Investor visa (~$100K+ investment, treaty-country citizens) and EB-5 ($800K+ for green card). Canada: Owner-Operator Work Permit (no minimum investment, but requires being CEO-level role), Start-Up Visa, and Permanent Residency via investment.',
      '## Foreign-buyer rules',
      'U.S.: largely open, but specific industries (defense, telecom, agriculture) require CFIUS review for foreign acquirers. Canada: Investment Canada Act may require approval for acquisitions above review thresholds (typically $1B+ for WTO-country buyers; lower for state-owned enterprises and cultural businesses).',
      '## Tax on profits',
      'U.S. C-corp federal rate 21% (+ state); pass-through entities flow to personal tax. Canada combined federal+provincial corporate rate ~25–27% on small business income up to $500K (small business deduction), ~12–15% effective. Personal tax on dividends/wages varies.',
      '## Cross-border deal logistics',
      'If a U.S. buyer acquires a Canadian business: structure typically involves a Canadian holdco. Tax treaties prevent double taxation but add complexity. Plan for currency hedging if the seller note is in CAD. Most cross-border deals add 30–60 days to close vs domestic.',
      '## Quick comparison',
      '- Average days to close: U.S. 90, Canada 110',
      '- Average SBA/CSBFP advance: U.S. ~75%, Canada ~70%',
      '- Average down payment: U.S. 10–15%, Canada 20–25%',
      '- Average seller-carry rate: U.S. 6–8%, Canada 5–7%',
      'Always engage local counsel and accountants in both jurisdictions for cross-border deals. The complexity is manageable; the surprises are expensive.',
    ],
  },
  {
    slug: 'uae-free-zone-vs-mainland-acquisition',
    title: 'UAE Free-Zone vs Mainland Business Acquisitions: What Buyers Need to Know',
    category: 'Buying',
    region: 'UAE',
    readMinutes: 8,
    excerpt: 'The single biggest structural decision in a UAE business acquisition. Here\'s how free-zone and mainland deals actually differ.',
    body: [
      '## The basic distinction',
      'UAE businesses operate under one of two regimes: **mainland** (regulated by the relevant emirate\'s Department of Economic Development — Dubai DED, Abu Dhabi ADDED, etc.) or **free zone** (regulated by one of 40+ free-zone authorities — DMCC, JAFZA, DIFC, ADGM, IFZA, SHAMS, and others). The licence type determines who you can sell to, where you can have offices, and how acquisitions work.',
      '## Mainland businesses',
      'Can serve customers anywhere in the UAE (and beyond). Since 2021 federal reforms, 100% foreign ownership is permitted in most mainland activities (a major change — previously required a UAE-national local sponsor). Acquisitions typically go through the issuing DED and involve a trade-licence amendment, share transfer registration, and employee visa transfers.',
      '## Free-zone businesses',
      'Operate within a specific free zone with rules set by that zone\'s authority. Generally cannot directly serve the UAE mainland market without a mainland distributor (a major operating constraint). 100% foreign ownership is the default. Acquisitions involve the specific free-zone authority, not the DED.',
      '## What changes in acquisition mechanics',
      '**Mainland:** Notarized share transfer agreement → DED submission → licence reissue → MOFA/MOL employee transfers → bank account amendments. Typically 4–8 weeks. **Free zone:** Free-zone authority application → board resolution → updated licence → visa amendments through the free zone\'s immigration desk. Typically 2–6 weeks. Free-zone deals are generally faster.',
      '## Free zones differ — a lot',
      'Not all free zones are equal. DMCC (Dubai Multi Commodities Centre) is the largest, with a broad activity list and good reputation. DIFC and ADGM are common-law financial-services zones with English-language courts (preferred by financial buyers). JAFZA suits industrial and logistics. IFZA, SHAMS, and others are lower-cost but with narrower activity scope. Always confirm the seller\'s free zone before LOI — your acquisition cost and timeline depend on it.',
      '## Activities and licenses',
      'Each licence lists permitted "activities" (sometimes hundreds, sometimes just one). Diligence whether the activity matches what the business actually does — a "wholesale trading" licence operating a retail business is a common compliance issue. Adding activities post-close is possible but costs time and money.',
      '## Beneficial ownership disclosure (UBO)',
      'Mandatory under Cabinet Decision 58/2020 across both mainland and free zone. Your acquisition will require updating UBO records. Forward Intelligence captures UBO during seller verification — useful for diligence.',
      '## Employee considerations',
      'Visa sponsorship transfers from the seller\'s entity to yours. Mainland: through MOHRE (Ministry of Human Resources and Emiratisation) and ICA. Free zone: through the zone\'s own immigration desk. End-of-service gratuity (severance based on tenure) is a real liability — diligence the accrual and decide whether it transfers or settles at close.',
      '## VAT and corporate tax',
      'VAT (5%) applies to mainland and to free-zone businesses with substantive UAE-mainland customers. Corporate tax (9% on profits over AED 375K, in effect since 2023) applies to mainland businesses; some free zones offer preferential rates for "qualifying income" — but the rules are nuanced. Get a tax advisor before LOI.',
      '## Banking and AML',
      'UAE banks have tightened account-opening dramatically. Plan for 30–60 days to open a new account post-acquisition; in some cases keeping the seller\'s entity (share sale) avoids the issue. AML obligations under Federal Decree-Law 20/2018 apply — particularly for cash-heavy businesses.',
      '## Practical recommendation',
      'For most acquirers: target mainland if you need direct UAE-market access; free zone if international trade and 100% foreign ownership simplicity matters most. Get a UAE-based corporate lawyer in week 1 — they\'ll save you months of friction.',
    ],
  },
]

export interface GlossaryTerm { term: string; definition: string }

export const GLOSSARY: GlossaryTerm[] = [
  { term: 'SDE', definition: 'Seller\'s Discretionary Earnings — earnings available to a single owner-operator, adding back owner salary and discretionary costs.' },
  { term: 'EBITDA', definition: 'Earnings Before Interest, Taxes, Depreciation, and Amortisation — a standard profitability measure for valuing larger businesses.' },
  { term: 'EBITDA Multiple', definition: 'The factor applied to EBITDA to estimate enterprise value; varies by industry, growth, and risk.' },
  { term: 'Earnout', definition: 'A portion of the purchase price paid later, contingent on the business hitting agreed performance targets.' },
  { term: 'LOI', definition: 'Letter of Intent — a mostly non-binding document outlining price and key terms before due diligence.' },
  { term: 'DSCR', definition: 'Debt-Service Coverage Ratio — annual cash flow divided by annual debt payments. Lenders typically want 1.25× or more.' },
  { term: 'CSBFP', definition: 'Canada Small Business Financing Program — a government-backed loan program (via major banks) for equipment, property, and business purchases up to $1.15M.' },
  { term: 'BDC', definition: 'Business Development Bank of Canada — Canada\'s bank for entrepreneurs, offering acquisition and transition financing.' },
  { term: 'Murabaha', definition: 'A Sharia-compliant cost-plus sale where the financier buys an asset and resells it to the buyer at a disclosed mark-up, repaid in instalments.' },
  { term: 'Ijara', definition: 'A Sharia-compliant lease-to-own arrangement; the financier leases an asset to the buyer with ownership transferring at term end.' },
  { term: 'Seller Financing', definition: 'A vendor take-back note where the seller finances part of the purchase price, repaid over time — common in 20-40% of SMB deals.' },
  { term: 'Data Room', definition: 'A secure online repository where a seller shares confidential documents with vetted buyers, with access tracking and NDAs.' },
  { term: 'Sales-to-Ask Ratio', definition: 'The ratio of final sale price to original asking price — a gauge of pricing power and buyer negotiation leverage.' },
]

export function getArticle(slug: string): Article | undefined {
  return ARTICLES.find((a) => a.slug === slug)
}
